import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

export const adminApi = createApi({
  reducerPath: 'admin', // Define a unique name for your API slice within Redux store
  baseQuery: fetchBaseQuery({ baseUrl: 'http://localhost:3000/' }), // Set the base URL for API requests

  endpoints: (builder) => ({
    getAccounts: builder.query({
      query: () => `accounts`, // Define a query endpoint to fetch accounts data
      transformResponse: (response) => response.sort((a, b) => b.amount - a.amount), // Transform response to sort accounts by amount descending
      providesTags: ['accounts'], // Tag for caching mechanism
    }),

    addAccount: builder.mutation({
      query: (amount, id) => ({
        url: 'accounts',
        method: 'POST',
        body: { amount, id }, // Define a mutation endpoint to add an account
      }),
      invalidatesTags: ['accounts'], // Tag to invalidate cache upon mutation
    }),

    deleteAccount: builder.mutation({
      query: (id) => ({
        url: `accounts/${id}`,
        method: 'DELETE', // Define a mutation endpoint to delete an account by ID
      }),
      invalidatesTags: ['accounts'], // Tag to invalidate cache upon mutation
    }),

    updateAccount: builder.mutation({
      query: ({ id, amount }) => ({
        url: `accounts/${id}`,
        method: 'PATCH',
        body: { amount }, // Define a mutation endpoint to update an account's amount by ID
      }),
      invalidatesTags: ['accounts'], // Tag to invalidate cache upon mutation
    }),
  }),
});

// Export hooks generated by createApi for each endpoint
export const {
  useGetAccountsQuery,
  useAddAccountMutation,
  useDeleteAccountMutation,
  useUpdateAccountMutation,
} = adminApi;


// import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

// export const adminApi = createApi({
//   reducerPath: 'admin',
//   baseQuery: fetchBaseQuery({ baseUrl: 'http://localhost:3000/' }),
//   endpoints: (builder) => ({
//     getAccounts: builder.query({
//       query: () => `accounts`,
//       transformResponse:(response)=>response.sort((a,b)=>b.amount-a.amount),
//       providesTags: ['accounts'],
//     }),
//     addAccount: builder.mutation({
//       query: (amount, id) => ({
//         url: 'accounts',
//         method: 'POST',
//         body: { amount, id },
//       }),
//       invalidatesTags: ['accounts'],
//     }),
//     deleteAccount: builder.mutation({
//       query: (id) => ({
//         url: `accounts/${id}`,
//         method: 'DELETE',
//       }),
//       invalidatesTags: ['accounts'],
//     }),
//     updateAccount: builder.mutation({
//       query: ({id, amount}) => ({
//         url: `accounts/${id}`,
//         method: 'PATCH',
//         body: {amount},
//       }),
//       invalidatesTags: ['accounts'],
//     }),
//   }),
// });

// export const {
//   useGetAccountsQuery,
//   useAddAccountMutation,
//   useDeleteAccountMutation,
//   useUpdateAccountMutation
// } = adminApi;
